parent=keycloak
import=common/keycloak

styles=css/styles.css

kcCardDescription=Informe suas credenciais para continuar

meta.description=Onboarding Client Login Theme

registrationUrl=http://localhost:5173/register
