using System.Reflection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.DependencyInjection;
using NSubstitute;
using Shouldly;

namespace Onboarding.API.Tests.Filters;

/// <summary>
/// Unit tests for the internal IdempotentAttribute action filter (REG-08).
/// The type is internal to Onboarding.API so we access it via reflection + IAsyncActionFilter cast.
///
/// Scenarios:
/// - No Idempotency-Key header → passthrough (next called)
/// - Non-GUID Idempotency-Key header → passthrough (REG-08 silently ignores non-GUIDs)
/// - Cache hit (valid GUID key) → returns stored response without calling next
/// - Cache miss (valid GUID key) → calls next, caches 2xx response
/// - Cache miss + 4xx response → calls next, does NOT cache
/// - Cache miss + 5xx response → calls next, does NOT cache
/// </summary>
public class IdempotencyFilterTests
{
    // ── Filter instantiation via reflection (internal type) ───────────────────────

    // Program is generated by top-level statements in the global namespace.
    // We resolve the internal type via the API assembly at runtime.
    private static readonly Type IdempotentAttributeType =
        typeof(Program).Assembly
            .GetType("Onboarding.API.Filters.IdempotentAttribute", throwOnError: true)!;

    private static IAsyncActionFilter CreateFilter()
    {
        return (IAsyncActionFilter)Activator.CreateInstance(IdempotentAttributeType)!;
    }

    // ── ActionExecutingContext helpers ────────────────────────────────────────────

    private static (ActionExecutingContext, IDistributedCache) BuildContext(
        string? idempotencyKey = null,
        IServiceProvider? services = null)
    {
        var cache = Substitute.For<IDistributedCache>();

        if (services is null)
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddSingleton<IDistributedCache>(cache);
            services = serviceCollection.BuildServiceProvider();
        }

        var httpContext = new DefaultHttpContext { RequestServices = services };

        if (idempotencyKey is not null)
            httpContext.Request.Headers["Idempotency-Key"] = idempotencyKey;

        var actionContext = new ActionContext(
            httpContext,
            new RouteData(),
            new ActionDescriptor());

        var context = new ActionExecutingContext(
            actionContext,
            filters: new List<IFilterMetadata>(),
            actionArguments: new Dictionary<string, object?>(),
            controller: new object());

        return (context, cache);
    }

    private static ActionExecutionDelegate NextDelegate(ActionExecutedContext? executedCtx = null)
    {
        return () => Task.FromResult(executedCtx ?? new ActionExecutedContext(
            new ActionContext(
                new DefaultHttpContext(),
                new RouteData(),
                new ActionDescriptor()),
            new List<IFilterMetadata>(),
            controller: new object()));
    }

    private static ActionExecutionDelegate NextDelegateWithResult(IActionResult result)
    {
        var executed = new ActionExecutedContext(
            new ActionContext(
                new DefaultHttpContext(),
                new RouteData(),
                new ActionDescriptor()),
            new List<IFilterMetadata>(),
            controller: new object())
        {
            Result = result
        };

        return () => Task.FromResult(executed);
    }

    // ── No Idempotency-Key header → passthrough ───────────────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_NoIdempotencyKeyHeader_CallsNext()
    {
        var filter = CreateFilter();
        var (ctx, cache) = BuildContext(idempotencyKey: null);

        var nextCalled = false;
        ActionExecutionDelegate next = () =>
        {
            nextCalled = true;
            return Task.FromResult(NextDelegateWithResult(new OkResult()).Invoke().Result);
        };

        await filter.OnActionExecutionAsync(ctx, next);

        nextCalled.ShouldBeTrue("next must be called when no Idempotency-Key header is present");
        ctx.Result.ShouldBeNull("no short-circuit when header is absent");
    }

    [Fact]
    public async Task OnActionExecutionAsync_NoIdempotencyKeyHeader_DoesNotAccessCache()
    {
        var filter = CreateFilter();
        var (ctx, cache) = BuildContext(idempotencyKey: null);

        await filter.OnActionExecutionAsync(ctx, NextDelegate());

        // Cache must not be consulted when header is absent
        await cache.DidNotReceiveWithAnyArgs().GetAsync(default!, default);
    }

    // ── Non-GUID Idempotency-Key → passthrough (REG-08 silently ignores) ─────────

    [Fact]
    public async Task OnActionExecutionAsync_NonGuidKey_CallsNext()
    {
        var filter = CreateFilter();
        var (ctx, _) = BuildContext(idempotencyKey: "not-a-guid");

        var nextCalled = false;
        ActionExecutionDelegate next = () =>
        {
            nextCalled = true;
            return Task.FromResult(NextDelegate().Invoke().Result);
        };

        await filter.OnActionExecutionAsync(ctx, next);

        nextCalled.ShouldBeTrue("non-GUID key must be silently ignored and next called");
    }

    [Fact]
    public async Task OnActionExecutionAsync_EmptyStringKey_CallsNext()
    {
        var filter = CreateFilter();
        var (ctx, _) = BuildContext(idempotencyKey: "");

        var nextCalled = false;
        ActionExecutionDelegate next = () =>
        {
            nextCalled = true;
            return Task.FromResult(NextDelegate().Invoke().Result);
        };

        await filter.OnActionExecutionAsync(ctx, next);

        nextCalled.ShouldBeTrue("empty string key must be silently ignored and next called");
    }

    // ── Cache HIT → returns stored response, does NOT call next ──────────────────

    [Fact]
    public async Task OnActionExecutionAsync_CacheHit_SetsResultFromCache_DoesNotCallNext()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        // Serialize a stored response the same way the production code does
        var storedValue = new { value = "cached-body", status = 201 };
        var storedJson = System.Text.Json.JsonSerializer.Serialize(
            new { StatusCode = 201, Value = (object)"cached-body" });

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns(System.Text.Encoding.UTF8.GetBytes(storedJson));

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var nextCalled = false;
        ActionExecutionDelegate next = () =>
        {
            nextCalled = true;
            return Task.FromResult(NextDelegate().Invoke().Result);
        };

        await filter.OnActionExecutionAsync(ctx, next);

        nextCalled.ShouldBeFalse("next must NOT be called on cache hit");
        ctx.Result.ShouldNotBeNull("result must be set from cache");
        var objectResult = ctx.Result.ShouldBeOfType<ObjectResult>();
        objectResult.StatusCode.ShouldBe(201);
    }

    [Fact]
    public async Task OnActionExecutionAsync_CacheHit_ReturnsStoredStatusCode()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        // Production code deserializes IdempotentResponse(StatusCode, Value)
        var storedJson = System.Text.Json.JsonSerializer.Serialize(
            new { StatusCode = 201, Value = (object)new { id = "abc123" } });

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns(System.Text.Encoding.UTF8.GetBytes(storedJson));

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        await filter.OnActionExecutionAsync(ctx, NextDelegate());

        var objectResult = ctx.Result.ShouldBeOfType<ObjectResult>();
        objectResult.StatusCode.ShouldBe(201);
    }

    // ── Cache MISS + 2xx → calls next, caches response ───────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_2xxResult_CachesResponse()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        // GetAsync returns null (cache miss)
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("created") { StatusCode = 201 });

        await filter.OnActionExecutionAsync(ctx, next);

        // Verify SetAsync was called (response was cached)
        await cache.Received(1).SetAsync(
            $"idem:{key}",
            Arg.Any<byte[]>(),
            Arg.Any<DistributedCacheEntryOptions>(),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_200Result_CachesResponse()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("ok") { StatusCode = 200 });

        await filter.OnActionExecutionAsync(ctx, next);

        await cache.Received(1).SetAsync(
            $"idem:{key}",
            Arg.Any<byte[]>(),
            Arg.Any<DistributedCacheEntryOptions>(),
            Arg.Any<CancellationToken>());
    }

    // ── Cache MISS + 4xx → calls next, does NOT cache ────────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_400Result_DoesNotCache()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("bad request") { StatusCode = 400 });

        await filter.OnActionExecutionAsync(ctx, next);

        // SetAsync must NOT be called for 4xx responses
        await cache.DidNotReceiveWithAnyArgs().SetAsync(default!, default!, default!, default);
    }

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_422Result_DoesNotCache()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("validation error") { StatusCode = 422 });

        await filter.OnActionExecutionAsync(ctx, next);

        await cache.DidNotReceiveWithAnyArgs().SetAsync(default!, default!, default!, default);
    }

    // ── Cache MISS + 5xx → calls next, does NOT cache ────────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_500Result_DoesNotCache()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("server error") { StatusCode = 500 });

        await filter.OnActionExecutionAsync(ctx, next);

        await cache.DidNotReceiveWithAnyArgs().SetAsync(default!, default!, default!, default);
    }

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_503Result_DoesNotCache()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync($"idem:{key}", Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("unavailable") { StatusCode = 503 });

        await filter.OnActionExecutionAsync(ctx, next);

        await cache.DidNotReceiveWithAnyArgs().SetAsync(default!, default!, default!, default);
    }

    // ── Cache key format: "idem:{guid}" ─────────────────────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_UsesCacheKeyWithIdemPrefix()
    {
        var filter = CreateFilter();
        var key = "550e8400-e29b-41d4-a716-446655440000";

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        var next = NextDelegateWithResult(new ObjectResult("ok") { StatusCode = 201 });

        await filter.OnActionExecutionAsync(ctx, next);

        // Assert the exact cache key format used by the production code: "idem:{parsed-guid}"
        var parsedGuid = Guid.Parse(key);
        await cache.Received().GetAsync(
            $"idem:{parsedGuid}",
            Arg.Any<CancellationToken>());
    }

    // ── Cache TTL: 60 minutes ────────────────────────────────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_CacheMiss_2xxResult_CachesTtl60Minutes()
    {
        var filter = CreateFilter();
        var key = Guid.NewGuid().ToString();

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        DistributedCacheEntryOptions? capturedOptions = null;
        await cache.SetAsync(
            Arg.Any<string>(),
            Arg.Any<byte[]>(),
            Arg.Do<DistributedCacheEntryOptions>(o => capturedOptions = o),
            Arg.Any<CancellationToken>());

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        await filter.OnActionExecutionAsync(ctx,
            NextDelegateWithResult(new ObjectResult("ok") { StatusCode = 201 }));

        // TTL must be exactly 60 minutes as documented in the filter
        capturedOptions.ShouldNotBeNull();
        capturedOptions!.AbsoluteExpirationRelativeToNow.ShouldBe(TimeSpan.FromMinutes(60));
    }

    // ── Valid GUID formats ────────────────────────────────────────────────────────

    [Fact]
    public async Task OnActionExecutionAsync_BracedGuidKey_IsRecognizedAsValidGuid()
    {
        // Guid.TryParse accepts braced and hyphenated forms
        var filter = CreateFilter();
        var key = "{550e8400-e29b-41d4-a716-446655440000}";

        var cache = Substitute.For<IDistributedCache>();
        cache.GetAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
             .Returns((byte[]?)null);

        var services = new ServiceCollection();
        services.AddSingleton<IDistributedCache>(cache);
        var (ctx, _) = BuildContext(idempotencyKey: key, services: services.BuildServiceProvider());

        ActionExecutionDelegate next = () =>
        {
            var executed = new ActionExecutedContext(
                new ActionContext(new DefaultHttpContext(), new RouteData(), new ActionDescriptor()),
                new List<IFilterMetadata>(), new object())
            {
                Result = new ObjectResult("ok") { StatusCode = 201 }
            };
            return Task.FromResult(executed);
        };

        await filter.OnActionExecutionAsync(ctx, next);

        // A braced GUID is valid → next IS called (cache miss path, cache consulted)
        await cache.Received().GetAsync(Arg.Any<string>(), Arg.Any<CancellationToken>());
    }
}
