// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/api-proxy/api/api-proxy').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../$vinxi/spa/client').default>>>>
    }
  }
}
export {}